# Generated by Django 6.0.7 on 2026-09-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payable_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_date", models.DateField()),
                ("created_at", models.DateTimeField()),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchases",
                        to="inventory.inventorysupplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchases_purchase",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("manufactured_date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase_items",
                        to="inventory.inventoryproduct",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        db_column="purchase_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_purchaseitem",
                "managed": True,
            },
        ),
    ]
