# Generated by Django 6.0.7 on 2026-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("email", models.CharField(max_length=254)),
                ("address", models.TextField()),
                ("loyalty_points", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("member_since", models.DateField(blank=True, null=True)),
                ("membership_tier", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "customers_customer",
                "managed": True,
            },
        ),
    ]
