# Generated by Django 6.0.7 on 2026-09-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("drug_a", models.CharField(max_length=255)),
                ("drug_b", models.CharField(max_length=255)),
                ("interaction_level", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
                ("pair_key", models.CharField(max_length=511, unique=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_druginteraction",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "inventory_category",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryMedicineGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_medicinegroup",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventorySupplier",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=254)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "db_table": "inventory_supplier",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InventoryProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("barcode", models.CharField(max_length=100, unique=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.IntegerField()),
                ("reorder_level", models.IntegerField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("is_sensitive", models.BooleanField()),
                (
                    "box_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "strip_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pcs_per_box", models.IntegerField(blank=True, null=True)),
                ("pcs_per_strip", models.IntegerField(blank=True, null=True)),
                ("strips_per_box", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.inventorymedicinegroup",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.inventorysupplier",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product",
                "managed": True,
            },
        ),
    ]
