# Generated by Django 6.0.7 on 2026-09-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payable_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("payment_method", models.CharField(max_length=10)),
                ("sale_date", models.DateField()),
                ("created_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_column="customer_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_sale",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=10)),
                ("quantity_pcs", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sale_items",
                        to="inventory.inventoryproduct",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        db_column="sale_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sales_saleitem",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField()),
                (
                    "sale",
                    models.ForeignKey(
                        db_column="sale_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sales_salepayment",
                "managed": True,
            },
        ),
    ]
